FS=$1
for i in `ls ${FS}-thread1-ind*.log`; do sh $2 $i; done
echo .........
for i in `ls ${FS}-thread2-ind*.log`; do sh $2 $i; done
echo .........
for i in `ls ${FS}-thread4-ind*.log`; do sh $2 $i; done
echo .........
for i in `ls ${FS}-thread8-ind*.log`; do sh $2 $i; done
